"""Remove deprecated columns from models

Revision ID: 137a1063e76b
Revises: c3d4e5f6a7b8
Create Date: 2025-10-27 05:14:14.606798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137a1063e76b'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_groups', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('network_objects', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_column('flattened_service')
        batch_op.drop_column('flattened_destination')
        batch_op.drop_column('flattened_source')
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('service_groups', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False))
    op.add_column('services', sa.Column('last_seen_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.alter_column('services', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('services', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('service_groups', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False))
    op.add_column('service_groups', sa.Column('last_seen_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.alter_column('service_groups', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('service_groups', 'members',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('service_groups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_policy_service_members_id'), table_name='policy_service_members')
    op.drop_index(op.f('ix_policy_address_members_id'), table_name='policy_address_members')
    op.add_column('policies', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False))
    op.add_column('policies', sa.Column('last_seen_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('policies', sa.Column('flattened_source', sa.VARCHAR(), nullable=True))
    op.add_column('policies', sa.Column('flattened_destination', sa.VARCHAR(), nullable=True))
    op.add_column('policies', sa.Column('flattened_service', sa.VARCHAR(), nullable=True))
    op.alter_column('policies', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('policies', 'service',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('policies', 'destination',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('policies', 'source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('policies', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('policies', 'enable',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('policies', 'rule_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('network_objects', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False))
    op.add_column('network_objects', sa.Column('last_seen_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.alter_column('network_objects', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('network_objects', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('network_objects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('network_groups', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False))
    op.add_column('network_groups', sa.Column('last_seen_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.alter_column('network_groups', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('network_groups', 'members',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('network_groups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'devices', type_='unique')
    op.alter_column('devices', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('devices', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('devices', 'vendor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('devices', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('devices', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('change_logs', 'details',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('change_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('change_logs', 'object_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('change_logs', 'data_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('change_logs', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('change_logs', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
