"""Add policies and firewall_objects tables

Revision ID: 566f23a6c130
Revises: da9c4385c9d9
Create Date: 2025-10-16 10:49:06.117155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566f23a6c130'
down_revision: Union[str, Sequence[str], None] = 'da9c4385c9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firewall_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['firewall_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firewall_objects_id'), 'firewall_objects', ['id'], unique=False)
    op.create_index(op.f('ix_firewall_objects_name'), 'firewall_objects', ['name'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('destination_ip', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('raw_policy', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['firewall_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_name'), 'policies', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policies_name'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_firewall_objects_name'), table_name='firewall_objects')
    op.drop_index(op.f('ix_firewall_objects_id'), table_name='firewall_objects')
    op.drop_table('firewall_objects')
    # ### end Alembic commands ###
