"""Remove is_active and last_seen_at from models

Revision ID: c29811f76a1f
Revises: 775a087473c7
Create Date: 2025-10-22 00:40:02.360714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29811f76a1f'
down_revision: Union[str, Sequence[str], None] = '775a087473c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_groups', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_seen_at')

    with op.batch_alter_table('network_objects', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('service_groups', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_seen_at')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('last_seen_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('service_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('last_seen_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('network_objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('last_seen_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('network_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###
