"""Update Policy model with new columns

Revision ID: c78945939474
Revises: 210aae0bb159
Create Date: 2025-10-21 00:44:19.536394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78945939474'
down_revision: Union[str, Sequence[str], None] = '210aae0bb159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('vsys', sa.String(), nullable=True))
    op.add_column('policies', sa.Column('seq', sa.Integer(), nullable=True))
    op.add_column('policies', sa.Column('enable', sa.Boolean(), nullable=True))
    op.add_column('policies', sa.Column('source', sa.String(), nullable=True))
    op.add_column('policies', sa.Column('user', sa.String(), nullable=True))
    op.add_column('policies', sa.Column('destination', sa.String(), nullable=True))
    op.add_column('policies', sa.Column('application', sa.String(), nullable=True))
    op.add_column('policies', sa.Column('security_profile', sa.String(), nullable=True))
    op.add_column('policies', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('policies', 'destination_ip')
    op.drop_column('policies', 'source_ip')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('source_ip', sa.VARCHAR(), nullable=True))
    op.add_column('policies', sa.Column('destination_ip', sa.VARCHAR(), nullable=True))
    op.drop_column('policies', 'category')
    op.drop_column('policies', 'security_profile')
    op.drop_column('policies', 'application')
    op.drop_column('policies', 'destination')
    op.drop_column('policies', 'user')
    op.drop_column('policies', 'source')
    op.drop_column('policies', 'enable')
    op.drop_column('policies', 'seq')
    op.drop_column('policies', 'vsys')
    # ### end Alembic commands ###
