"""Create firewall_devices table

Revision ID: da9c4385c9d9
Revises:
Create Date: 2025-10-16 10:42:09.878325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9c4385c9d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firewall_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_index(op.f('ix_firewall_devices_id'), 'firewall_devices', ['id'], unique=False)
    op.create_index(op.f('ix_firewall_devices_name'), 'firewall_devices', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firewall_devices_name'), table_name='firewall_devices')
    op.drop_index(op.f('ix_firewall_devices_id'), table_name='firewall_devices')
    op.drop_table('firewall_devices')
    # ### end Alembic commands ###
