"""sync_history total_network_objects total_services 컬럼 추가

Revision ID: 09dd00061f54
Revises: 98af10f9d74d
Create Date: 2026-08-07 11:30:15.349484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09dd00061f54'
down_revision: Union[str, Sequence[str], None] = '98af10f9d74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_histories', sa.Column('total_network_objects', sa.Integer(), nullable=True))
    op.add_column('sync_histories', sa.Column('total_services', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_histories', 'total_services')
    op.drop_column('sync_histories', 'total_network_objects')
    # ### end Alembic commands ###
