"""add from_zone, to_zone, log_setting to policies

Revision ID: 13da5d437d69
Revises: ed78465f7817
Create Date: 2026-08-06 12:17:58.653473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13da5d437d69'
down_revision: Union[str, Sequence[str], None] = 'ed78465f7817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('from_zone', sa.String(), nullable=True))
    op.add_column('policies', sa.Column('to_zone', sa.String(), nullable=True))
    op.add_column('policies', sa.Column('log_setting', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'log_setting')
    op.drop_column('policies', 'to_zone')
    op.drop_column('policies', 'from_zone')
    # ### end Alembic commands ###
