"""add export_tasks table

Revision ID: 98af10f9d74d
Revises: 13da5d437d69
Create Date: 2026-08-06 13:18:02.918250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98af10f9d74d'
down_revision: Union[str, Sequence[str], None] = '13da5d437d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_ids', sa.JSON(), nullable=False),
    sa.Column('export_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('merge', sa.Boolean(), nullable=False),
    sa.Column('use_ssh', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('step', sa.String(), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('result_file_path', sa.String(), nullable=True),
    sa.Column('result_filename', sa.String(), nullable=True),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('requested_by_username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_tasks_id'), 'export_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_tasks_id'), table_name='export_tasks')
    op.drop_table('export_tasks')
    # ### end Alembic commands ###
