"""add pending_policy_changes table

Revision ID: ed78465f7817
Revises: a3f7c9d1e246
Create Date: 2026-08-06 10:55:49.721978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed78465f7817'
down_revision: Union[str, Sequence[str], None] = 'a3f7c9d1e246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_policy_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('target_policy_id', sa.Integer(), nullable=True),
    sa.Column('client_key', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['target_policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pending_policy_changes_device', 'pending_policy_changes', ['device_id'], unique=False)
    op.create_index(op.f('ix_pending_policy_changes_id'), 'pending_policy_changes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_policy_changes_id'), table_name='pending_policy_changes')
    op.drop_index('ix_pending_policy_changes_device', table_name='pending_policy_changes')
    op.drop_table('pending_policy_changes')
    # ### end Alembic commands ###
